version: '3'
services:

  web:
    build: .
    restart: always
    container_name: flask
    command: bash -c "
      gunicorn wsgi:app -b 0.0.0.0:8000 --reload"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
